// Dependant variables_webComponents/src/app/child-view/child-view.ts
import { html, css, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { defineComponents, IgcButtonComponent, IgcCardComponent, IgcCheckboxComponent, IgcIconButtonComponent, IgcIconComponent, IgcInputComponent, IgcRippleComponent, IgcSliderComponent } from 'igniteui-webcomponents';
import { Subject, takeUntil } from 'rxjs';
import { OrderDetailDto } from '../models/north-windv-2api/order-detail-dto';
import '@infragistics/igniteui-webcomponents-grids/grids/combined.js';
import { OrderDto } from '../models/north-windv-2api/order-dto';
import { northWindv2APIService } from '../services/NorthWindv2API-service';

defineComponents(IgcCardComponent, IgcButtonComponent, IgcRippleComponent, IgcIconButtonComponent, IgcIconComponent, IgcSliderComponent, IgcInputComponent, IgcCheckboxComponent);

@customElement('app-child-view')
export default class ChildView extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
    }
    .column-layout {
      display: flex;
      flex-direction: column;
    }
    .group {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      min-width: 50px;
      min-height: 50px;
      flex-grow: 1;
      flex-basis: 0;
    }
    .row-layout {
      display: flex;
    }
    .group_1 {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      min-width: 50px;
      min-height: 50px;
    }
    .card {
      width: 320px;
      height: max-content;
      min-width: 320px;
      flex-shrink: 0;
    }
    .grid {
      min-width: 600px;
      min-height: 300px;
      flex-grow: 1;
      flex-basis: 0;
    }
    .actions-content {
      min-width: 50px;
      min-height: 40px;
    }
    .button {
      height: max-content;
    }
    .text {
      height: max-content;
      min-width: min-content;
    }
  `;

  constructor() {
    super();
    northWindv2APIService.selectedOrder.pipe(takeUntil(this.destroy$)).subscribe(() => northWindv2APIService.getOrderDetailDtoList(northWindv2APIService.selectedOrder.value?.orderId as any).then(
        (data) => {this.orderDetails = data}, 
        (err) => this.orderDetails = []));
    northWindv2APIService.selectedCustomer.pipe(takeUntil(this.destroy$)).subscribe(() => northWindv2APIService.getOrderDtoList(northWindv2APIService.selectedCustomer.value?.customerId as any).then(
        // orderDetails depends on selectedCustomer
        (data) => { this.northWindv2APIOrderDto = data;
                    this.orderDetails = [];}, 
        (err) => this.northWindv2APIOrderDto = []));
  }

  @state()
  private _orderDetails: OrderDetailDto[] = []; 

  get orderDetails(): OrderDetailDto[]  {
      return this._orderDetails;
  }

  set orderDetails(value: OrderDetailDto[] ) {
      this._orderDetails = value;
      // quantity, discount, testVar and orderDate depends on orderDetails
      this.quantity = undefined; 
      this.discount = undefined;
      this.orderDate = undefined;
      this.testVar = false;
  }

  @state()
  private _orderId?: number; 

  get orderId(): number | undefined  {
      return this._orderId;
  }

  set orderId(value: number | undefined) {
      this._orderId = value;
      // quantity, discount, testVar and orderDate depends on orderDetails
      this.quantity = undefined; 
      this.discount = undefined;
      this.orderDate = undefined;
      this.testVar = false;

      console.log('this.testVar: ' + this.testVar);
  }

  @state()
  private northWindv2APIOrderDto: OrderDto[] = [];

  @state()
  private quantity?: number;

  @state()
  private discount?: number;

  @state()
	private orderDate?: Date = new Date('2023-11-14T15:25');

	@state()
	private testVar?: boolean = true;

  @state()
  private destroy$: Subject<void> = new Subject<void>();

  public gridRowSelectionChanging(event: any) {
    northWindv2APIService.selectedOrder.next(event.detail.newSelection[0] as OrderDto);
  }

  public buttonClick(item: OrderDetailDto) {
    this.quantity = item.quantity as number;
  }

  public iconButtonClick(item: OrderDetailDto) {
    this.discount = item.discount as number;
  }

  public templateButtonClick(item: any) {
    console.log(item);
    this.orderId = item as number;
  }  

  // TODO this in front of ctx is a bug
  public columnBodyTemplate = (ctx: any) => html`
    <igc-button size="large" @click="${() => this.templateButtonClick(ctx.cell.value)}" class="button_1">
      ${ctx.cell.value}
      <igc-ripple></igc-ripple>
    </igc-button>
  `

  disconnectedCallback() {
    this.destroy$.next();
    this.destroy$.complete();
    super.disconnectedCallback();
  }

  render() {
    return html`
      <link href='https://fonts.googleapis.com/icon?family=Material+Icons' rel='stylesheet'>
      <link rel='stylesheet' href='../../ig-theme.css'>
      <link rel='stylesheet' href='node_modules/@infragistics/igniteui-webcomponents-grids/grids/themes/dark/bootstrap.css'>
      <div class="column-layout group">
        <div class="row-layout group">
          <igc-grid .data="${this.northWindv2APIOrderDto}" primary-key="orderId" display-density="cosy" row-selection="single" allow-filtering="true" filter-mode="excelStyleFilter" auto-generate="false" 
          @rowSelectionChanging="${this.gridRowSelectionChanging}" class="ig-typography ig-scrollbar grid">
            <igc-column field="orderId" data-type="number" header="orderId" sortable="true" selectable="false" .bodyTemplate="${this.columnBodyTemplate}"></igc-column>
            <igc-column field="customerId" data-type="string" header="customerId" sortable="true" selectable="false"></igc-column>            
            <igc-column field="employeeId" data-type="number" header="employeeId" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipperId" data-type="number" header="shipperId" sortable="true" selectable="false"></igc-column>            
            <igc-column field="orderDate" data-type="string" header="orderDate" sortable="true" selectable="false"></igc-column>
            <igc-column field="requiredDate" data-type="string" header="requiredDate" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipVia" data-type="number" header="shipVia" sortable="true" selectable="false"></igc-column>
            <igc-column field="freight" data-type="number" header="freight" sortable="true" selectable="false"></igc-column>            
            <igc-column field="shipName" data-type="string" header="shipName" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipAddress.street" data-type="string" header="shipAddress street" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipAddress.city" data-type="string" header="shipAddress city" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipAddress.region" data-type="string" header="shipAddress region" sortable="true" selectable="false"></igc-column>            
            <igc-column field="shipAddress.postalCode" data-type="string" header="shipAddress postalCode" sortable="true" selectable="false"></igc-column>
            <igc-column field="shipAddress.country" data-type="string" header="shipAddress country" sortable="true" selectable="false"></igc-column>            
            <igc-column field="shipAddress.phone" data-type="string" header="shipAddress phone" sortable="true" selectable="false"></igc-column>
          </igc-grid>
        </div>
        <div class="column-layout group">
          <div class="row-layout group_1">
            ${this.orderDetails?.map((item) => html`
              <igc-card class="card">
                <igc-card-header>
                  <h3 slot="title">
                    ${item.productId}
                  </h3>
                  <h5 slot="subtitle">
                    ${item.unitPrice}
                  </h5>
                </igc-card-header>
                <igc-card-actions class="actions-content">
                  <igc-button variant="flat" slot="start" size="large" @click="${() => this.buttonClick(item)}" class="button">
                    Button
                    <igc-ripple></igc-ripple>
                  </igc-button>
                  <igc-icon-button slot="end" variant="flat" @click="${() => this.iconButtonClick(item)}">
                    <span class="material-icons">
                      favorite
                    </span>
                    <igc-ripple></igc-ripple>
                  </igc-icon-button>
                  <igc-icon-button slot="end" variant="flat">
                    <span class="material-icons">
                      bookmark
                    </span>
                    <igc-ripple></igc-ripple>
                  </igc-icon-button>
                  <igc-icon-button slot="end" variant="flat">
                    <span class="material-icons">
                      share
                    </span>
                    <igc-ripple></igc-ripple>
                  </igc-icon-button>
                </igc-card-actions>
              </igc-card>
            `)}
          </div>
          <div class="row-layout group_1">
            <p class="typography__body-1 text">
              ${this.quantity}
            </p>
          </div>
          <div class="row-layout group_1">
            <p class="typography__body-1 text">
              ${this.discount}
            </p>
          </div>
          <div class="row-layout group_1">
						<igc-slider .value="${this.quantity!}" min="0" max="100" step="1" ?discrete-track="${true}" class="slider" style="width: 500px"></igc-slider>
					</div>
					<div class="row-layout group_1">
						<igc-input .value="${northWindv2APIService.selectedOrder.value?.shipName}" label="Label/Placeholder" ?outlined="${true}" class="input"></igc-input>
					</div>
					<div class="row-layout group_1">
						<igc-checkbox labelPosition="after" ?checked="${this.testVar}" class="checkbox">
							Label
						</igc-checkbox>
					</div>
					<div class="row-layout group_1">
						<span class="date-picker">DatePicker not yet available in WebComponents</span>
					</div>
        </div>
      </div>
    `;
  }
}

// Dependent variables_react/src/app/child-view/child-view.tsx
import { useGlobalContext } from '../hooks/context-hooks';
import { useGetOrderDetailDtoList, useGetOrderDtoList } from '../hooks/north-windv2-api-hooks';
import { OrderDto } from '../models/NorthWindv2API/order-dto';
import { IgrAvatar, IgrAvatarModule, IgrButton, IgrButtonModule, IgrCard, IgrCardActions, IgrCardHeader, IgrCardModule, IgrCheckbox, IgrCheckboxModule, IgrIconButton, IgrIconButtonModule, IgrInput, IgrInputModule, IgrList, IgrListItem, IgrListModule, IgrRipple, IgrRippleModule, IgrSlider, IgrSliderModule } from 'igniteui-react';
import { IgrCellTemplateContext, IgrColumn, IgrGrid, IgrGridBaseDirective, IgrGridModule, IgrRowSelectionEventArgs } from 'igniteui-react-grids';
import { IgrDatePicker, IgrDatePickerModule } from 'igniteui-react-inputs';
import { useEffect, useRef, useState } from 'react';
import 'igniteui-react-grids/grids';
import styles from './child-view.module.css';
import createClassTransformer from '../style-utils';

IgrAvatarModule.register();
IgrButtonModule.register();
IgrCardModule.register();
IgrCheckboxModule.register();
IgrDatePickerModule.register();
IgrGridModule.register();
IgrIconButtonModule.register();
IgrInputModule.register();
IgrListModule.register();
IgrRippleModule.register();
IgrSliderModule.register();

export default function ChildView() {
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();
  const __loaded = useRef<boolean>(false);
  const { globalState, setGlobalState } = useGlobalContext();
  const [_orderId, setOrderId] = useState<number | undefined>();
  const [quantity, setQuantity] = useState<number | undefined>();
  const [_orderDate, setOrderDate] = useState<Date | undefined>(new Date('2024-07-03T00:00'));
  const [testVar, setTestVar] = useState<boolean | undefined>(true);
  const [discount, setDiscount] = useState<number | undefined>();
  const { northWindv2APIOrderDetailDto: orderDetails, setNorthWindv2APIOrderDetailDto: setOrderDetails } = useGetOrderDetailDtoList(globalState.selectedOrder?.orderId as any);
  const { northWindv2APIOrderDto } = useGetOrderDtoList(globalState.selectedCustomer?.customerId as any);
  const { northWindv2APIOrderDto: northWindv2APIOrderDto1 } = useGetOrderDtoList(globalState.selectedCustomer?.customerId as any);

  useEffect(() => {
    if (__loaded.current) {
      setQuantity(undefined);
      setOrderDate(undefined);
      setTestVar(false);
      setDiscount(undefined);
    }
  }, [_orderId]);

  useEffect(() => {
    if (__loaded.current) {
      setQuantity(undefined);
      setOrderDate(undefined);
      setTestVar(false);
      setDiscount(undefined);
    }
  }, [orderDetails]);

  useEffect(() => {
    if (__loaded.current) {
      setOrderDetails([]);
    }
  }, [globalState.selectedOrder]);

  useEffect(() => {
    __loaded.current = true;
    return () => {
      __loaded.current = false;
    }
  }, []);

  function gridRowSelectionChanging(_: IgrGridBaseDirective, event: IgrRowSelectionEventArgs) {
    setGlobalState(prevState => ({...prevState, selectedOrder: event.detail.newSelection[0] as OrderDto}));
  }

  const columnBodyTemplate = (ctx: { dataContext: IgrCellTemplateContext }) => {
    return (
      <>
        <IgrButton size="large" clicked={() => setOrderId(ctx.dataContext.cell.value)} className={classes("button")}>
          <span key={uuid()}>{ctx.dataContext.cell.value}</span>
          <IgrRipple key={uuid()}></IgrRipple>
        </IgrButton>
      </>
    )
  }

  return (
    <>
      <div className={classes("row-layout child-view-container")}>
        <div className={classes("column-layout group")}>
          <div className={classes("row-layout group")}>
            <IgrList className={classes("list")}>
              {northWindv2APIOrderDto?.map((item) => (
                <div style={{display: 'contents'}} onClick={() => setGlobalState(prevState => ({...prevState, selectedOrder: item}))} key={uuid()}>
                  <IgrListItem>
                    <div style={{display: 'contents'}} slot="start" key={uuid()}>
                      <IgrAvatar shape="circle">
                        <span className={classes("material-icons")} key={uuid()}>
                          <span key={uuid()}>person</span>
                        </span>
                      </IgrAvatar>
                    </div>
                    <div slot="title" key={uuid()}>{item.orderId}</div>
                    <div slot="subtitle" key={uuid()}>{item.customerId}</div>
                    <span slot="end" className={classes("material-icons icon")} key={uuid()}>
                      <span key={uuid()}>star</span>
                    </span>
                  </IgrListItem>
                </div>
              ))}
            </IgrList>
            <IgrGrid data={northWindv2APIOrderDto1} primaryKey="orderId" displayDensity="cosy" rowSelection="single" allowFiltering="true" filterMode="excelStyleFilter" rowSelectionChanging={(s, event) => gridRowSelectionChanging(s, event)} className={classes("ig-typography ig-scrollbar grid")} key={uuid()}>
              <IgrColumn field="orderId" dataType="number" header="orderId" sortable="true" bodyTemplate={columnBodyTemplate} selectable="false"></IgrColumn>
              <IgrColumn field="customerId" dataType="string" header="customerId" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="employeeId" dataType="number" header="employeeId" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipperId" dataType="number" header="shipperId" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="orderDate" dataType="string" header="orderDate" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="requiredDate" dataType="string" header="requiredDate" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipVia" dataType="number" header="shipVia" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="freight" dataType="number" header="freight" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipName" dataType="string" header="shipName" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.street" dataType="string" header="shipAddress street" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.city" dataType="string" header="shipAddress city" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.region" dataType="string" header="shipAddress region" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.postalCode" dataType="string" header="shipAddress postalCode" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.country" dataType="string" header="shipAddress country" sortable="true" selectable="false"></IgrColumn>
              <IgrColumn field="shipAddress.phone" dataType="string" header="shipAddress phone" sortable="true" selectable="false"></IgrColumn>
            </IgrGrid>
          </div>
          <div className={classes("row-layout group")}>
            <div className={classes("column-layout group_1")}>
              <p className={classes("typography__body-1 text")}>
                <span>*Select an item from the list (instead of the grid) to update the selectedOrder variable.
The grid flickers when data is updated which is breaking the row selection behavior in this sample. Additional details at:</span>
              </p>
              <a href="https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30691" className={classes("typography__body-1 hyperlink")}>
                <span>https://infragistics.visualstudio.com/Indigo_Platform/_workitems/edit/30691</span>
              </a>
            </div>
          </div>
          <div className={classes("column-layout group")}>
            <div className={classes("row-layout group_1")}>
              {orderDetails?.map((item) => (
                <IgrCard className={classes("card")} key={uuid()}>
                  <IgrCardHeader key={uuid()}>
                    <h3 slot="title" key={uuid()}>
                      <span key={uuid()}>{item.productId}</span>
                    </h3>
                    <h5 slot="subtitle" key={uuid()}>
                      <span key={uuid()}>{item.unitPrice}</span>
                    </h5>
                  </IgrCardHeader>
                  <IgrCardActions className={classes("actions-content")} key={uuid()}>
                    <div style={{display: 'contents'}} slot="start" key={uuid()}>
                      <IgrButton variant="flat" size="large" clicked={() => setQuantity(item.quantity)} className={classes("button")}>
                        <span key={uuid()}>Button</span>
                        <IgrRipple key={uuid()}></IgrRipple>
                      </IgrButton>
                    </div>
                    <div style={{display: 'contents'}} slot="end" key={uuid()}>
                      <IgrIconButton variant="flat" clicked={() => setDiscount(item.discount)}>
                        <span className={classes("material-icons")} key={uuid()}>
                          <span key={uuid()}>favorite</span>
                        </span>
                        <IgrRipple key={uuid()}></IgrRipple>
                      </IgrIconButton>
                    </div>
                    <div style={{display: 'contents'}} slot="end" key={uuid()}>
                      <IgrIconButton variant="flat">
                        <span className={classes("material-icons")} key={uuid()}>
                          <span key={uuid()}>bookmark</span>
                        </span>
                        <IgrRipple key={uuid()}></IgrRipple>
                      </IgrIconButton>
                    </div>
                    <div style={{display: 'contents'}} slot="end" key={uuid()}>
                      <IgrIconButton variant="flat">
                        <span className={classes("material-icons")} key={uuid()}>
                          <span key={uuid()}>share</span>
                        </span>
                        <IgrRipple key={uuid()}></IgrRipple>
                      </IgrIconButton>
                    </div>
                  </IgrCardActions>
                </IgrCard>
              ))}
            </div>
            <div className={classes("row-layout group_1")}>
              <p className={classes("typography__body-1 text")}>
                <span>{quantity!}</span>
              </p>
            </div>
            <div className={classes("row-layout group_1")}>
              <p className={classes("typography__body-1 text")}>
                <span>{discount!}</span>
              </p>
            </div>
            <div className={classes("row-layout group_1")}>
              <IgrSlider value={quantity!} min="0" max="100" step="1" discreteTrack="true" className={classes("slider")}></IgrSlider>
            </div>
            <div className={classes("row-layout group_1")}>
              <IgrInput value={globalState.selectedOrder?.shipName} label="ShipName" outlined="true" className={classes("input")}></IgrInput>
            </div>
            <div className={classes("row-layout group_1")}>
              <IgrCheckbox labelPosition="after" checked={testVar} className={classes("checkbox")}>
                <span key={uuid()}>Label</span>
              </IgrCheckbox>
            </div>
            <div className={classes("row-layout group_1")}>
              <div className={classes("group_2")}>
                <IgrDatePicker label="Date"></IgrDatePicker>
              </div>
            </div>
            <div className={classes("row-layout group_1")}>
              <p className={classes("typography__body-1 text")}>
                <span>*Date Picker is not assigned to orderDate variable as the variable could be undefined: </span>
              </p>
              <a href="https://github.com/IgniteUI/igniteui-webcomponents/issues/1205" className={classes("typography__body-1 hyperlink_1")}>
                <span>https://github.com/IgniteUI/igniteui-webcomponents/issues/1205</span>
              </a>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
